#ifndef __FBHYPERLINKTYPE_H__
#define __FBHYPERLINKTYPE_H__

enum FBHyperlinkType {
	HYPERLINK_NONE = 0,
	HYPERLINK_INTERNAL = 1,
	HYPERLINK_EXTERNAL = 2,
	//HYPERLINK_BOOK = 3,
};

#endif /* __FBHYPERLINKTYPE_H__ */
